# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15MMlqiZm7OZpQXx2k5chMajOQwaSt9is
"""

import numpy as np
import pickle
import streamlit as st


# loading the saved model
loaded_model = pickle.load(open('model.sav', 'rb'))

def prediction(input_data):
  # input_data = (5,166,72,19,175,25.8,0.587)

  # changing the input_data to numpy array
  input_data_as_numpy_array = np.asarray(input_data)

  # reshape the array as we are predicting for one instance
  input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

  # Perform the prediction
  result = loaded_model.predict(input_data_reshaped)

  return result[0]

def main():
  st.title("Find Calories")


  #getting the input data from the user

  Gender       = st.text_input("Enter Your gender")
  Age	         = st.text_input("Enter Your Age")
  Height       = st.text_input("Enter Your Height")
  Weight       = st.text_input("Enter Your Weight")
  Duration     = st.text_input("Enter Your Duration")
  Heart_Rate	 = st.text_input("Enter Your Heart Rate")
  Body_Temp	   = st.text_input("Enter Your Body Temprature")

  #code for prediction
  result = ''

  #creating a button for prediction

  # Create a button for prediction
  if st.button("Calculate Calories"):
    try:
      # Convert inputs to the correct type
      input_data = [
        int(Gender),  # Assuming gender is encoded as an integer
        float(Age),
        float(Height),
        float(Weight),
        float(Duration),
        float(Heart_Rate),
        float(Body_Temp)
      ]

      result = prediction(input_data)
    except ValueError as e:
      st.error(f"Invalid input: {e}")
    except Exception as e:
      st.error(f"An error occurred: {e}")

  st.success(result)



if __name__ == '__main__':
  main()